# Smart contracts test and lint pipeline
image: node:16

pipelines:
  default:
    - parallel:
        - step:
            name: Compile and Test
            caches:
              - node
            script:
              - yarn install
              - yarn compile
              - yarn test
        - step:
            name: Code linting TS
            script:
              - yarn lint:ts
            caches:
              - node

        - step:
            name: Code linting SOL
            script:
              - yarn lint:sol
            caches:
              - node
