on: [push, pull_request]

# on:
#   push:
#     branches:
#       - main
#   pull_request:
    # Optionally configure to run only for changes in specific files. For example:
    # paths:
    # - src/**
    # - test/**
    # - foundry.toml
    # - remappings.txt
    # - .github/workflows/foundry-gas-diff.yml

name: Forge Tests

# https://github.com/Rubilmax/foundry-gas-diff
env:
  # make fuzzing semi-deterministic to avoid noisy gas cost estimation
  # due to non-deterministic fuzzing (but still use pseudo-random fuzzing seeds)
  FOUNDRY_FUZZ_SEED: 0x${{ github.event.pull_request.base.sha || github.sha }}


jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run tests
        run: forge test -vvv --gas-report

      - name: Run snapshot
        run: forge snapshot
